# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: maven包install

#只有当release分支发布才执行
#on:
#  release:
#    types: [created]

# 当main分支被提交就执行
on:
  push:
    branches: [ "maven" ]
#支持手动执行 测试
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: 设置java版本
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: maven创建打包
      run: mvn -B package --file pom.xml

# github package : https://docs.github.com/zh/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry
# git action: https://docs.github.com/zh/actions/publishing-packages/publishing-java-packages-with-maven
    - name: 上传到GitHub Packages 
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
